import { useState } from "react";
import { updateCVVisibility } from "../services/cv.service";

const defaultVisibility = {
  personalData: {
    showPersonalData: true,
    showPersonalDataForPublic: true,
    showUniversity: true,
    showUniversityForPublic: true,
    showAuthority: true,
    showAuthorityForPublic: true,
    showDepartment: true,
    showDepartmentForPublic: true,
    showBirthDate: true,
    showBirthDateForPublic: true,
    showProfilePicture: true,
    showProfilePictureForPublic: true,
    showSkills: true,
    showSkillsForPublic: true,
  },
  contactInfo: {
    showContactInfo: true,
    showContactInfoForPublic: true,
    showMainPhone: true,
    showMainPhoneForPublic: true,
    showWorkPhone: true,
    showWorkPhoneForPublic: true,
    showOfficialEmail: true,
    showOfficialEmailForPublic: true,
    showFax: true,
    showFaxForPublic: true,
  },
  socialMedia: {
    showSocialMedia: true,
    showSocialMediaForPublic: true,
    showLinkedIn: true,
    showLinkedInForPublic: true,
    showInstagram: true,
    showInstagramForPublic: true,
    showPersonalWebsite: true,
    showPersonalWebsiteForPublic: true,
    showGoogleScholar: true,
    showGoogleScholarForPublic: true,
    showScopus: true,
    showScopusForPublic: true,
    showFacebook: true,
    showFacebookForPublic: true,
    showX: true,
    showXForPublic: true,
    showYouTube: true,
    showYouTubeForPublic: true,
  },
  academicQualifications: {
    showAcademicQualifications: true,
    showAcademicQualificationsForPublic: true,
    showQualification: true,
    showQualificationForPublic: true,
    showSpecialization: true,
    showSpecializationForPublic: true,
    showGrade: true,
    showGradeForPublic: true,
    showDispatchType: true,
    showDispatchTypeForPublic: true,
    showUniversityOrFaculty: true,
    showUniversityOrFacultyForPublic: true,
    showCountryOrCity: true,
    showCountryOrCityForPublic: true,
    showDateOfObtainingTheQualification: true,
    showDateOfObtainingTheQualificationForPublic: true,
  },
  jobRanks: {
    showJobRanks: true,
    showJobRanksForPublic: true,
    showJobRank: true,
    showJobRankForPublic: true,
    showDateOfJobRank: true,
    showDateOfJobRankForPublic: true,
  },
  administrativePositions: {
    showAdministrativePositions: true,
    showAdministrativePositionsForPublic: true,
    showPosition: true,
    showPositionForPublic: true,
    showPositionStartDate: true,
    showPositionStartDateForPublic: true,
    showPositionEndDate: true,
    showPositionEndDateForPublic: true,
  },
  conferencesAndSeminars: {
    showConferencesAndSeminars: true,
    showConferencesAndSeminarsForPublic: true,
    showConferenceOrSeminarName: true,
    showConferenceOrSeminarNameForPublic: true,
    showConferenceOrSeminarRoleOfParticipation: true,
    showConferenceOrSeminarRoleOfParticipationForPublic: true,
    showConferenceOrSeminarOrganizingAuthority: true,
    showConferenceOrSeminarOrganizingAuthorityForPublic: true,
    showConferenceOrSeminarWebsite: true,
    showConferenceOrSeminarWebsiteForPublic: true,
    showConferenceOrSeminarStartDate: true,
    showConferenceOrSeminarStartDateForPublic: true,
    showConferenceOrSeminarEndDate: true,
    showConferenceOrSeminarEndDateForPublic: true,
    showConferenceOrSeminarVenue: true,
    showConferenceOrSeminarVenueForPublic: true,
  },
  scientificMissions: {
    showScientificMissions: true,
    showScientificMissionsForPublic: true,
    showMissionName: true,
    showMissionNameForPublic: true,
    showMissionStartDate: true,
    showMissionStartDateForPublic: true,
    showMissionEndDate: true,
    showMissionEndDateForPublic: true,
    showMissionUniversityOrFaculty: true,
    showMissionUniversityOrFacultyForPublic: true,
    showMissionCountryOrCity: true,
    showMissionCountryOrCityForPublic: true,
  },
  trainingPrograms: {
    showTrainingPrograms: true,
    showTrainingProgramsForPublic: true,
    showTrainingProgramName: true,
    showTrainingProgramNameForPublic: true,
    showTrainingProgramVenue: true,
    showTrainingProgramVenueForPublic: true,
    showTrainingProgramStartDate: true,
    showTrainingProgramStartDateForPublic: true,
    showTrainingProgramEndDate: true,
    showTrainingProgramEndDateForPublic: true,
  },
  committeesAndAssociations: {
    showCommitteesAndAssociations: true,
    showCommitteesAndAssociationsForPublic: true,
    showNameOfCommitteeOrAssociation: true,
    showNameOfCommitteeOrAssociationForPublic: true,
    showTypeOfCommitteeOrAssociation: true,
    showTypeOfCommitteeOrAssociationForPublic: true,
    showDegreeOfSubscription: true,
    showDegreeOfSubscriptionForPublic: true,
    showCommitteesAndAssociationsStartDate: true,
    showCommitteesAndAssociationsStartDateForPublic: true,
    showCommitteesAndAssociationsEndDate: true,
    showCommitteesAndAssociationsEndDateForPublic: true,
  },
  participationInMagazines: {
    showParticipationInMagazines: true,
    showParticipationInMagazinesForPublic: true,
    showNameOfMagazine: true,
    showNameOfMagazineForPublic: true,
    showWebsiteOfMagazine: true,
    showWebsiteOfMagazineForPublic: true,
    showTypeOfParticipation: true,
    showTypeOfParticipationForPublic: true,
  },
  reviewingArticles: {
    showReviewingArticles: true,
    showReviewingArticlesForPublic: true,
    showTitleOfArticle: true,
    showTitleOfArticleForPublic: true,
    showAuthority: true,
    showAuthorityForPublic: true,
    showReviewingDate: true,
    showReviewingDateForPublic: true,
  },
  projects: {
    showProjects: true,
    showProjectsForPublic: true,
    showNameOfProject: true,
    showNameOfProjectForPublic: true,
    showTypeOfProject: true,
    showTypeOfProjectForPublic: true,
    showParticipationRole: true,
    showParticipationRoleForPublic: true,
    showFinancingAuthority: true,
    showFinancingAuthorityForPublic: true,
    showProjectStartDate: true,
    showProjectStartDateForPublic: true,
    showProjectEndDate: true,
    showProjectEndDateForPublic: true,
  },
  teachingExperiences: {
    showTeachingExperiences: true,
    showTeachingExperiencesForPublic: true,
    showCourseName: true,
    showCourseNameForPublic: true,
    showAcademicLevel: true,
    showAcademicLevelForPublic: true,
    showUniversityOrFaculty: true,
    showUniversityOrFacultyForPublic: true,
    showTeachingExperienceStartDate: true,
    showTeachingExperienceStartDateForPublic: true,
    showTeachingExperienceEndDate: true,
    showTeachingExperienceEndDateForPublic: true,
  },
  generalExperiences: {
    showGeneralExperiences: true,
    showGeneralExperiencesForPublic: true,
    showExperienceTitle: true,
    showExperienceTitleForPublic: true,
    showAuthority: true,
    showAuthorityForPublic: true,
    showCountryOrCity: true,
    showCountryOrCityForPublic: true,
    showStartDate: true,
    showStartDateForPublic: true,
    showEndDate: true,
    showEndDateForPublic: true,
  },
  scientificWritings: {
    showScientificWritings: true,
    showScientificWritingsForPublic: true,
    showTitle: true,
    showTitleForPublic: true,
    showAuthorRole: true,
    showAuthorRoleForPublic: true,
    showISBN: true,
    showISBNForPublic: true,
    showPublishingHouse: true,
    showPublishingHouseForPublic: true,
    showPublishingDate: true,
    showPublishingDateForPublic: true,
  },
  patents: {
    showPatents: true,
    showPatentsForPublic: true,
    showNameOfPatent: true,
    showNameOfPatentForPublic: true,
    showAccreditingAuthorityOrCountry: true,
    showAccreditingAuthorityOrCountryForPublic: true,
    showAccreditationDate: true,
    showAccreditationDateForPublic: true,
  },
  prizesAndRewards: {
    showPrizesAndRewards: true,
    showPrizesAndRewardsForPublic: true,
    showPrizeName: true,
    showPrizeNameForPublic: true,
    showawardingAuthority: true,
    showawardingAuthorityForPublic: true,
    showDateReceived: true,
    showDateReceivedForPublic: true,
  },
  manifestationsOfScientificAppreciation: {
    showManifestationsOfScientificAppreciation: true,
    showManifestationsOfScientificAppreciationForPublic: true,
    showTitleOfAppreciation: true,
    showTitleOfAppreciationForPublic: true,
    showIssuingAuthority: true,
    showIssuingAuthorityForPublic: true,
    showDateOfAppreciation: true,
    showDateOfAppreciationForPublic: true,
  },
  contributionsToCommunityService: {
    showContributionsToCommunityService: true,
    showContributionsToCommunityServiceForPublic: true,
    showContributionTitle: true,
    showContributionTitleForPublic: true,
    showDateOfContribution: true,
    showDateOfContributionForPublic: true,
  },
  contributionsToUniversity: {
    showContributionsToUniversity: true,
    showContributionsToUniversityForPublic: true,
    showContributionTitle: true,
    showContributionTitleForPublic: true,
    showTypeOfContribution: true,
    showTypeOfContributionForPublic: true,
    showDateOfContribution: true,
    showDateOfContributionForPublic: true,
  },
  participationInQualityWork: {
    showparticipationsInQualityWork: true,
    showparticipationsInQualityWorkForPublic: true,
    showparticipationTitle: true,
    showparticipationTitleForPublic: true,
    showParticipationStartDate: true,
    showParticipationStartDateForPublic: true,
    showParticipationEndDate: true,
    showParticipationEndDateForPublic: true,
  },
};

export { defaultVisibility };

export default function useCVManage() {
  const [visibility, setVisibility] = useState(defaultVisibility);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  const toggle = (section, field) => {
    setVisibility((prev) => ({
      ...prev,
      [section]: {
        ...prev[section],
        [field]: !prev[section][field],
      },
    }));
  };

  const save = async () => {
    setLoading(true);
    setError(null);
    setSuccess(false);
    try {
      await updateCVVisibility(visibility);
      setSuccess(true);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  };

  return { visibility, toggle, save, loading, error, success, setSuccess };
}
